export enum TableName {
  Users = 'users',
  Identities = 'identities',
  Portfolios = 'portfolios',
  Positions = 'positions',
  Trades = 'trades',
  CronJobs = 'cronJobs',
  CronJobRuns = 'cronJobRuns',
  Agents = 'agents',
  Activity = 'activity',
  PortfolioEodValueHistory = 'portfolioEodValueHistory',
  OverviewEodValueHistory = 'overviewEodValueHistory',
  PortfolioIntradayValueHistory = 'portfolioIntradayValueHistory',
  OverviewIntradayValueHistory = 'overviewIntradayValueHistory',
  StockResearch = 'stockResearch',
  Briefing = 'briefing',
  BrokerConnections = 'brokerConnections',
  DeviceTokens = 'deviceTokens',
}

export enum GsiName {
  IdentitiesByUser = 'identitiesByUser',
  PortfoliosByUser = 'portfoliosByUser',
  CronJobsByUser = 'cronJobsByUser',
  CronJobsByPortfolio = 'cronJobsByPortfolio',
  CronJobRunsByPortfolio = 'cronJobRunsByPortfolio',
  CronJobRunsByTime = 'cronJobRunsByTime',
  RunsByPortfolioTime = 'runsByPortfolioTime',
  AgentsByPortfolio = 'agentsByPortfolio',
  ActivityByPortfolio = 'activityByPortfolio',
  TradesByCronJob = 'tradesByCronJob',
  TradesByPortfolioTime = 'tradesByPortfolioTime',
  PortfolioEodValueHistoryByUser = 'portfolioEodValueHistoryByUser',
}
